#! /bin/sh

[ -n "$ZSH_VERSION" ] && setopt +o nomatch # Remove glob errors if zsh is used

conf_file=~/.tunnel

parse()
{
  eval "$1=$(sed -n "s/$1[[:space:]]*=[[:space:]]*\(.*\)/\1/p" $2)"
}

check_active_tunnels()
{
  ls /tmp/tunnel-*.cfg > /dev/null 2>&1 &&
    return 0

  echo "No active tunnel"
  return 1
}

check_status()
{
  for file in /tmp/tunnel-${2:-*}.cfg; do
    parse local_port "$file"
    parse ssh_port "$file"
    parse target "$file"
    curl -m 2 127.0.0.1:"$local_port" > /dev/null 2>&1
    "$1" "$?" "$local_port" "$ssh_port"
  done
}

print_status()
{
  printf "tunnel: %s -> %s (%s)" "$local_port" "$ssh_port" "$target"
  if [ "$1" -eq 0 ]; then
    printf '\033[0;32m OK\033[0m\n'
  else
    printf '\033[0;31m KO\033[0m\n'
  fi
}

stop_tunnel()
{
  if [ -f "/tmp/tunnel-$1.cfg" ]; then
    parse pid "/tmp/tunnel-$1.cfg"
    if [ "$(ps -p "$pid" -o comm=)" = 'ssh' ]; then
      kill -s TERM "$pid"
    fi
  fi
}

create_ssh_tunnel()
{
  if [ "$1" -ne 0 ]; then
    stop_tunnel "$2"
    ssh -fNL "$2:$target:$3" "$address" >> /tmp/tunnel-"$2".log 2>&1
    printf "local_port=%s\nssh_port=%s\ntarget=%s\n" "$2" "$3" "$target" > /tmp/tunnel-"$2".cfg
    ps_ouput="$(ps aux)"
    pid="$(printf '%s' "$ps_ouput" | sed -n "s/[^[:space:]]*[[:space:]]*\([^[:space:]]*\).*ssh -fNL $2.*/\1/p")"
    printf 'pid=%s\n' "$pid" >> /tmp/tunnel-"$2".cfg
  fi
}

clean()
{
  if [ "$1" -ne 0 ]; then
    stop_tunnel "$2"
    rm /tmp/tunnel-"$2".*
  fi
}

if [ -f "$conf_file" ]; then
  parse address "$conf_file"
  parse target  "$conf_file"
  : ${target:=localhost}
else
  printf "Enter your ssh address\n> "
  read address
  printf "Enter your tunnel target\n> "
  read target
  printf 'address=%s\ntarget=%s\n' "$address" "$target" > ~/.tunnel
  echo
fi

if [ "$#" -lt 1 ]; then
  check_active_tunnels
  if [ "$?" -eq 0 ]; then
    check_status print_status
  fi
else
  case "$1" in
    stop|s)
      if [ -z "$2" ]; then
        for file in /tmp/tunnel-*.cfg; do
          parse local_port "$file"
          stop_tunnel "$local_port"
        done
      else
        stop_tunnel "$2"
      fi
      ;;
    restart|r)
      check_status create_ssh_tunnel "$2"
      ;;
    clean|c)
      check_status clean "$2"
      ;;
    config|cfg)
      ${EDITOR:-vi} ~/.tunnel
      ;;
    help|h|--help|-h)
      echo 'Usage: tunnel [options]

      Displays tunnels status when launched with no options.

      Options:

            local-port  distant-port     creates a tunnel from your your ssh address on distant-port to localhost on local-port
            stop, s     [local-port]     stops local-port tunnel or all tunnels if no port is specified
            clean, c    [local-port]     removes local-port tunnel if stopped or all stopped tunnels if no port is specified
            restart, r  [local-port]     restarts local-port tunnel if stopped or all stopped tunnels if no port is specified
            config, cfg                  opens the configuration file with your default editor
      '
      ;;
    *)
      if [ "$#" -eq 2 ] && [ "$1" -gt 0 ] && [ "$2" -gt 0 ]; then
        create_ssh_tunnel 1 "$1" "$2"
      else
        echo 'tunnel: Invalid Command' >&2
        exit 1
      fi
      ;;
  esac
fi
